apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-filestore
provisioner: filestore.csi.storage.gke.io
parameters:
  tier: enterprise
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
